Transform: AWS::Serverless-2016-10-31
Description: A SAM template for deploying two lambda functions

Resources:
  Lambda1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "lambda1"
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: ../../lambda1
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  Lambda1:
    Description: "ARN of the first Lambda function"
    Value: !GetAtt Lambda1.Arn