AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template for deploying two lambda functions

Parameters:
  PRId:
    Type: String
    Default: "latest"
    Description: "The unique PR identifier"
  
  Environment:
    Type: String
    AllowedValues: [test, qa, prod]
    Description: "The deployment environment"

Conditions:
  IsTest: !Equals [ !Ref Environment, "test" ]
  IsQA: !Equals [ !Ref Environment, "qa" ]
  IsProd: !Equals [ !Ref Environment, "prod" ]

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs20.x
    MemorySize: 128

Resources:
  Lambda1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "lambda1"
      CodeUri: ../lambda1
      Policies:
        - AWSLambdaBasicExecutionRole

  Lambda1Version:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref Lambda1

  Lambda1Alias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref Lambda1
      FunctionVersion: !Ref Lambda1Version
      Name: !Ref PRId
      Description: !Sub "Alias for ${PRId}"

  Lambda2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "lambda2"
      CodeUri: ../lambda2
      Policies:
        - AWSLambdaBasicExecutionRole

  Lambda2Version:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref Lambda2

  Lambda2Alias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref Lambda2
      FunctionVersion: !Ref Lambda2Version
      Name: !Ref PRId
      Description: !Sub "Alias for ${PRId}"

Outputs:
  Lambda1:
    Description: "ARN of the first Lambda function"
    Value: !GetAtt Lambda1.Arn
  Lambda2:
    Description: "ARN of the second Lambda function"
    Value: !GetAtt Lambda2.Arn