AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template for a gateway with some functions
Parameters:
  Environment:
    Type: String
    AllowedValues: [qa, uat, prod]
    Description: The deployment environment
  DeploymentTarget:
    Type: String
    AllowedValues: [blue, green]
    Default: blue
    Description: Target of the blue/green deployment for the prod environment
  GitHubAccessToken:
    Type: String
    NoEcho: true
    MinLength: 1
    Description: Token used by Amplify to connect to the remote repository
  GitHubRepoURL:
    Type: String
    AllowedPattern: \bhttps?://(www\.)?github\.com/[A-Za-z0-9_-]+/[A-Za-z0-9._-]+(\.git)?/?\b
    ConstraintDescription: value must be a valid GitHub HTTP URL
    Default: https://github.com/raffallves/actions-fe.git
    Description: Remote repository url
Conditions:
  # IsUAT: !Equals [!Ref Environment, uat]
  IsProd: !Equals [!Ref Environment, prod]
Mappings:
  ResourceNameMapping:
    prod:
      blue: prod-blue
      green: prod-green
    qa:
      blue: qa
      green: qa
Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs20.x
    MemorySize: 128
    AutoPublishAlias: !Ref Environment
Resources:
  Lambda3:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 
        - "lambda3-${sufix}"
        - sufix: !FindInMap [ResourceNameMapping, !Ref Environment, !Ref DeploymentTarget]
      CodeUri: ../lambda1
      Policies:
        - AWSLambdaBasicExecutionRole
  Lambda4:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 
        - "lambda4-${sufix}"
        - sufix: !FindInMap [ResourceNameMapping, !Ref Environment, !Ref DeploymentTarget]
      CodeUri: ../lambda2
      Policies:
        - AWSLambdaBasicExecutionRole
  Gateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 
        - "app-endpoints-${sufix}"
        - sufix: !FindInMap [ResourceNameMapping, !Ref Environment, !Ref DeploymentTarget]
      StageName: !Ref Environment
      AlwaysDeploy: false
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./api-definitions.yml
    Connectors:
      LambdasConn:
        Properties:
          Destination:
            - Id: Lambda3
            - Id: Lambda4
          Permissions:
            - Write
  App:
    Type: AWS::Amplify::App
    Condition: IsProd
    Properties:
      AccessToken: !Ref GitHubAccessToken
      BuildSpec: |
        version: 1
        frontend:
          phases:
            preBuild:
              commands:
                - npm ci --cache .npm --prefer-offline
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: dist
            files:
              - '**/*'
          cache:
            paths:
              - .npm/**/*
      CacheConfig: 
        Type: AMPLIFY_MANAGED_NO_COOKIES
      Description: Hosting for the React front-end app
      Name: !Join ["-", [dapp, !Ref Environment, !Ref DeploymentTarget]]
      Repository: !Ref GitHubRepoURL
      AutoBranchCreationConfig:
        EnableAutoBranchCreation: false
  FrontEndBranch:
    Type: AWS::Amplify::Branch
    Condition: IsProd
    Properties:
      AppId: !GetAtt App.AppId
      BranchName: main
      EnableAutoBuild: false
      EnablePullRequestPreview: false
      EnablePerformanceMode: false
      EnvironmentVariables:
        - Name: VITE_API_URL
          Value: !Sub "https://${Gateway.RootResourceId}.execute-api.${AWS::Region}.amazonaws.com/${Environment}"
Outputs:
  Lambda3:
    Description: ARN of the first Lambda function
    Value: !GetAtt Lambda3.Arn
  Lambda4:
    Description: ARN of the second Lambda function
    Value: !GetAtt Lambda4.Arn
  Gateway:
    Description: Gateway resource ID
    Value: !GetAtt Gateway.RootResourceId
  App:
    Description: Name of the hosted app
    Value: !GetAtt App.AppName
    Condition: IsProd
  FrontEndBranch:
    Description: Deployed branch
    Value: !GetAtt FrontEndBranch.BranchName
    Condition: IsProd