AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A SAM template for deploying two lambda functions

Parameters:
  NewAliasName:
    Type: String
    Default: "latest"

Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs20.x
    AutoPublishAlias: !Ref NewAliasName
    MemorySize: 128

Resources:
  Lambda1:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "lambda1"
      CodeUri: ../lambda1
      Policies:
        - AWSLambdaBasicExecutionRole

  Lambda2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "lambda2"
      CodeUri: ../lambda2
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  Lambda1:
    Description: "ARN of the first Lambda function"
    Value: !GetAtt Lambda1.Arn
  Lambda2:
    Description: "ARN of the second Lambda function"
    Value: !GetAtt Lambda2.Arn