Transform: AWS::Serverless-2016-10-31
Description: A SAM template for deploying two lambda functions

Resources:
  Lambda2:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "lambda2"
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: ../../lambda2
      MemorySize: 128
      Policies:
        - AWSLambdaBasicExecutionRole

Outputs:
  Lambda2:
    Description: "ARN of the second Lambda function"
    Value: !GetAtt Lambda2.Arn