name: Deploying lambdas separately
run-name: lemme c

env:
  PR_ID: pr${{ github.event.pull_request.number }}

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      contents: read
    outputs:
      changed_lambdas: ${{ steps.filter.outputs.changed_dirs }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Filter lambdas to deploy to test env
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            changed_dirs:
              - '**'
              exclude:
                - 'sam/**'
                - '.github/**'
                - package.json
                - package-lock.json
                - .gitignore
  
  deploy:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.changed_lambdas == 'true'
    strategy:
      matrix:
        directory: ${{ fromJson(needs.filter.outputs.changed_lambdas) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Deploy ${{ matrix.directory }} function
        run: |
          cd ${{ matrix.directory }}
          aws lambda update-function-code \
            --function-name ${{ matrix.directory }} \
            --zip-file fileb://index.mjs
