name: Deploying lambdas separately
run-name: lemme c
on: [push]
jobs:
  Deploying-Lambdas:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Build
        run: |
          cd sam
          sam build -t template.yml

      - name: Deploy
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          ALIAS_NAME="pr-${PR_NUMBER}"
          sam deploy -t template.yml \
          --no-confirm-changeset \
          --no-fail-on-empty-changeset \
          --parameter-overrides NewAliasName=${ALIAS_NAME}